"""add strategy_performance_daily

Revision ID: 1675f13299a7
Revises: e422ed7afe74
Create Date: 2026-04-18 16:57:37.850658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1675f13299a7'
down_revision: Union[str, None] = 'e422ed7afe74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_performance_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('firm', sa.String(length=64), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_winner', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('avg_loser', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sharpe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('recovery_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('best_day_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('worst_day_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_name', 'as_of_date', 'window_days', name='uq_perf_strategy_date_window')
    )
    op.create_index(op.f('ix_strategy_performance_daily_as_of_date'), 'strategy_performance_daily', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_strategy_performance_daily_strategy_name'), 'strategy_performance_daily', ['strategy_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_performance_daily_strategy_name'), table_name='strategy_performance_daily')
    op.drop_index(op.f('ix_strategy_performance_daily_as_of_date'), table_name='strategy_performance_daily')
    op.drop_table('strategy_performance_daily')
    # ### end Alembic commands ###
