"""add strategy_heartbeats

Revision ID: 32ee9a7d4dc6
Revises: 89fecabef2a1
Create Date: 2026-04-18 21:16:33.569828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '32ee9a7d4dc6'
down_revision: Union[str, None] = '89fecabef2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_heartbeats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('firm', sa.String(length=64), nullable=False),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('last_decision', sa.String(length=128), nullable=False),
    sa.Column('iteration_count_today', sa.Integer(), nullable=False),
    sa.Column('iterations_total', sa.Integer(), nullable=False),
    sa.Column('sleeptime', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_heartbeats')
    # ### end Alembic commands ###
