"""add backtest_runs

Revision ID: 89fecabef2a1
Revises: 1675f13299a7
Create Date: 2026-04-18 17:23:36.733450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89fecabef2a1'
down_revision: Union[str, None] = '1675f13299a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('data_source', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('final_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sharpe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('trades_csv_path', sa.String(length=256), nullable=True),
    sa.Column('tearsheet_path', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_strategy_name'), 'backtest_runs', ['strategy_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_runs_strategy_name'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
