"""baseline schema

Revision ID: e422ed7afe74
Revises: 
Create Date: 2026-04-18 16:31:12.296358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e422ed7afe74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firm', sa.String(length=64), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('account_size', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('peak_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_drawdown_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('weekly_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monthly_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('PAPER', 'CHALLENGE', 'FUNDED', name='account_mode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'HALTED', 'PASSED', 'BLOWN', name='account_status'), nullable=False),
    sa.Column('broker_account_ref', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm', 'strategy_name', name='uq_account_firm_strategy')
    )
    op.create_table('news_windows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event', 'starts_at', 'currency', name='uq_news_event_start_ccy')
    )
    op.create_index(op.f('ix_news_windows_event'), 'news_windows', ['event'], unique=False)
    op.create_index(op.f('ix_news_windows_starts_at'), 'news_windows', ['starts_at'], unique=False)
    op.create_table('strategy_daily_pnl',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('firm', sa.String(length=64), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm', 'strategy_name', 'trade_date', name='uq_strategy_pnl_day')
    )
    op.create_index(op.f('ix_strategy_daily_pnl_firm'), 'strategy_daily_pnl', ['firm'], unique=False)
    op.create_index(op.f('ix_strategy_daily_pnl_strategy_name'), 'strategy_daily_pnl', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_strategy_daily_pnl_trade_date'), 'strategy_daily_pnl', ['trade_date'], unique=False)
    op.create_table('daily_summary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_winner', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('avg_loser', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_drawdown_intraday', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('consistency_rule_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('daily_loss_limit_used_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'summary_date', name='uq_daily_summary_account_date')
    )
    op.create_index(op.f('ix_daily_summary_account_id'), 'daily_summary', ['account_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='trade_direction'), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exit_reason', sa.Enum('SIGNAL', 'STOP', 'TAKE_PROFIT', 'TIME', 'RISK_HALT', 'MANUAL', name='exit_reason'), nullable=True),
    sa.Column('market_regime', sa.Enum('TRENDING', 'RANGING', 'VOLATILE', 'UNKNOWN', name='market_regime'), nullable=True),
    sa.Column('vix_at_entry', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('hour_of_entry', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('PAPER', 'CHALLENGE', 'FUNDED', name='trade_mode'), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_trades_asset'), 'trades', ['asset'], unique=False)
    op.create_index(op.f('ix_trades_entry_time'), 'trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trades_strategy_name'), 'trades', ['strategy_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_strategy_name'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_time'), table_name='trades')
    op.drop_index(op.f('ix_trades_asset'), table_name='trades')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_daily_summary_account_id'), table_name='daily_summary')
    op.drop_table('daily_summary')
    op.drop_index(op.f('ix_strategy_daily_pnl_trade_date'), table_name='strategy_daily_pnl')
    op.drop_index(op.f('ix_strategy_daily_pnl_strategy_name'), table_name='strategy_daily_pnl')
    op.drop_index(op.f('ix_strategy_daily_pnl_firm'), table_name='strategy_daily_pnl')
    op.drop_table('strategy_daily_pnl')
    op.drop_index(op.f('ix_news_windows_starts_at'), table_name='news_windows')
    op.drop_index(op.f('ix_news_windows_event'), table_name='news_windows')
    op.drop_table('news_windows')
    op.drop_table('accounts')
    # ### end Alembic commands ###
